### ISSUE TITLE
Removing the use of pkg-info

### ISSUE THREAD

**Issue by sergeyklay** [sergeyklay/bnf-mode#1]
Thanks - merging now!

BTW, I strongly recommend removing the use of `pkg-info` and particularly the `bnf-mode-version` function, which is almost the biggest piece of code in this little package. Users can easily call `describe-package` (built-in) or `pkg-info-package-version` interactively if they want to get this information.

_Originally posted by @purcell in https://github.com/melpa/melpa/pull/6074#issuecomment-475916422_

**Comment by sboosali** [comment]
iiuc, why not provide an `defalias` for `pkg-info-package-version`?

like

    (defalias 'bnf-mode-version #'pkg-info-package-version)

**Comment by sboosali** [comment]
(anecdotally, i write a lot of elisp, and didn't know about pkg-info-package-version until now. yesterday, i tried running `use-package-version`.)

**Comment by sergeyklay** [comment]
Frankly speaking, I can't find a compelling reason to duplicate this functionality.
